---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
  description: Backstage Admins
spec:
  type: team
  profile:
    displayName: Admins
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
  description: Developer users
spec:
  type: team
  profile:
    displayName: Developers
    email: developers-all@serverlessops.io
  children: []