---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  description: Backstage ECS Service & Task
  annotations:
    github.com/project-slug: ServerlessOpsIO/backstage-app
spec:
  type: application
  lifecycle: production
  owner: group:00gjdgxs1ur6lsu
  system: backstage
  domain: infrastructure
  dependsOn:
    - resource:backstage-app-container
    - resource:backstage-cluster
    - resource:backstage-db

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-app-container
  description: Backstage ECS Service
  annotations:
    github.com/project-slug: ServerlessOpsIO/backstage-app
    io.serverlessops/cluster-type: ecs
spec:
  type: container-service
  lifecycle: production
  owner: group:00gjdgxs1ur6lsu
  system: backstage
  domain: infrastructure
  dependsOn:
    - resource:backstage-cluster
