---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: domain-add
  title: Add Application Domain
  description: Add a new application domain to Backstage
  tags:
    - catalog
spec:
  type: domain
  owner: group:admins

  parameters:
    - title: Domain information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Domain
          type: string
          description: Name of application domain
          ui:autofocus: true
          ui:placeholder: eg. Infrastructure, Cloud, AI
        description:
          title: Description
          description: Description of application domain
          type: string
        owner:
          title: Owner
          description: Owner of the domain
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Group
        kind:
          title: Kind
          description: Kind of entity
          type: string
          ui:widget: hidden
          default: Domain
        namespace:
          title: Namespace
          description: Namespace of domain
          type: string
          ui:widget: hidden
          default: default
  steps:
    - id: create-severlessops-entity
      name: Creating entity in ServerlessOps Catalog
      action: serverlessops:catalog:create
      input:
        title: ${{parameters.name}}
        name: ${{parameters.name | lower}}
        description: ${{parameters.description}}
        owner: ${{parameters.owner}}
        kind: ${{parameters.kind}}
        namespace: ${{parameters.namespace}}
    # FIXME: using addLocation just adds a new location to the catalog which is then processed
    # and that's not what we want because the URL location processor doesn't have creds for
    # this service.
    #- id: register-backstage-entity
    #  name: Registering entity in Backstage
    #  action: serverlessops:catalog:register
    #  input:
    #    catalogInfoUrl: https://api.catalog.backstage.serverlessops.io/catalog/${{parameters.namespace}}/${{parameters.kind | lower}}/${{parameters.name | lower}}