---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: system-add
  title: Add Application System
  description: Add a new application system to Backstage
  tags:
    - catalog
spec:
  type: system
  owner: group:admins

  parameters:
    - title: System information
      required:
        - domain
        - name
        - description
        - owner
      properties:
        domain:
          title: Domain
          type: string
          description: Domain of application system
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain
        name:
          title: System
          type: string
          description: Name of application system
          ui:placeholder: eg. Backstage, Infra Services
        description:
          title: Description
          description: Description of application system
          type: string
        owner:
          title: Owner
          description: Owner of the system
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Group
        kind:
          title: Kind
          description: Kind of entity
          type: string
          ui:widget: hidden
          default: System
        namespace:
          title: Namespace
          description: Namespace of system
          type: string
          ui:widget: hidden
          default: default
  steps:
    - id: create-severlessops-entity
      name: Creating entity in ServerlessOps Catalog
      action: serverlessops:catalog:create
      input:
        name: ${{parameters.name}}
        description: ${{parameters.description}}
        owner: ${{parameters.owner}}
        kind: ${{parameters.kind}}
        namespace: ${{parameters.namespace}}
        domain: ${{parameters.domain}}
    # FIXME: using addLocation just adds a new location to the catalog which is then processed
    # and that's not what we want because the URL location processor doesn't have creds for
    # this service.
    #- id: register-backstage-entity
    #  name: Registering entity in Backstage
    #  action: serverlessops:catalog:register
    #  input:
    #    catalogInfoUrl: https://api.catalog.backstage.serverlessops.io/catalog/${{parameters.namespace}}/${{parameters.kind | lower}}/${{parameters.name | lower}}