app:
  title: Backstage Portal
  baseUrl: http://${DNS_NAME}:7007

backend:
  baseUrl: http://${DNS_NAME}:7007
  database:
    connection:
      ssl: null

auth:
  environment: home
  providers:
    guest: null
    github:
      home:
        clientId: ${GITHUB_AUTH_CLIENT_ID}
        clientSecret: ${GITHUB_AUTH_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail