app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://${DNS_NAME}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: https://${DNS_NAME}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen:
    listen: 0.0.0.0 # Bind to all interfaces
    port: 7007

  # config options: https://node-postgres.com/apis/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        ca: # if you have a CA file and want to verify it you can uncomment this section
          $file: rds-combined-ca-bundle.pem
  reading:
    allow:
      - host: api.catalog.backstage.serverlessops.io

auth:
  environment: production
  providers:
    guest: null
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
        signIn:
          resolvers:
            # typically you would pick one of these
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
            - resolver: emailMatchingUserEntityAnnotation

integrations:
  github:
    - host: github.com
      apps:
        - $include: /app/app-config.d/github-app-credentials.yaml

catalog:
  providers:
    serverlessops-catalog:
      baseUrl: ${SERVERLESSOPS_CATALOG_API_URL}
      namespace: default
      entityKinds:
        - Domain
        - System
        - Resource
        - Users
        - Group
      auth:
        endpoint: ${SERVERLESSOPS_AUTH_ENDPOINT}
        clientId: ${SERVERLESSOPS_AUTH_CLIENT_ID}
        clientSecret: ${SERVERLESSOPS_AUTH_CLIENT_SECRET}
      schedule:
        initialDelay: { seconds: 5 }
        frequency: { hours: 1 }
        timeout: { seconds: 60 }

  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  locations:
    - type: file
      target: /app/app-config.d/catalogs/users.yaml
      rules:
        - allow: [User]
    - type: file
      target: /app/app-config.d/catalogs/groups.yaml
      rules:
        - allow: [Groups]
    - type: file
      target: /app/app-config.d/scaffolders/domain-add.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../app-config.d/scaffolders/system-add.yaml
      rules:
        - allow: [Template]